# Check if a Prebuilt-MPR package needs updated.
name: Check Package
run-name: "Check Package: '${{ inputs.pkgbase }}'"
on:
  workflow_dispatch:
    inputs:
      pkgbase:
        required: true
        type: string

jobs:
  check-pkg:
    name: Check Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Prebuilt-MPR APT repository
        uses: makedeb/setup-makedeb@main
        with:
          makedeb-repo: false
          pbmpr-repo: true
      - name: Download Prebuilt-MPR helper binary
        run: gh release download -p pbmpr
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - name: Make Prebuilt-MPR helper binary executable
        run: chmod +x ./pbmpr
      - name: Run update checks for the specified package
        run: sudo rm /etc/apt/sources.list.d/* && sudo -E ./pbmpr check-pkg "${{ inputs.pkgbase }}"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
