name: Check Issue
on:
  issues:
    types: [opened]
env:
  GH_TOKEN: "${{ github.token }}"
  GH_REPO: "${{ github.repository }}"

jobs:
  check-issue:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Redirect issue to GitHub discussions
        run: gh issue close "${{ github.event.issue.number }}" -c "The issue tracker for this project is used to manage package updates. If you have a question/issue with the Prebuilt-MPR, please use the [issues category on the Discussions page](https://github.com/makedeb/prebuilt-mpr/discussions/categories/issues)."
