# Update an MPR package.
name: Update Package
on:
  workflow_dispatch:
    inputs:
      # A JSON array. The array items are objects containing these keys:
      # - 'arch'
      # - 'codename'
      # - 'image-tag'
      targets:
        required: true
        type: string

jobs:
  update-pkg:
    name: Build Package (${{ matrix.codename }} - ${{ matrix.arch }})
    runs-on: ubuntu-latest
    needs: get-distro-image-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.targets) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build package
        run: echo "${SCRIPT}" | docker run -i proget.hunterwittenborn.com/docker/makedeb/makedeb:${{ matrix.image-tag }} bash
        env:
          SCRIPT: |
            echo "HEEEEEY!"
      # - name: Install prerequisites
      #   run: sudo apt install git locales-all -y
      # - name: Correct permissions so makedeb can run
      #   run: chown 'makedeb:makedeb' ./ "${HOME}" -R
      # - name: Run makedeb
      #   run: sudo -Eu makedeb makedeb -s --no-confirm --pass-env
      #   env:
      #     DEBIAN_FRONTEND: "${{ vars.DEBIAN_FRONTEND }}"
      #     # Needed to extract some tar archives.
      #     LANG: "en_US.UTF-8"
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.distro-image }}
      #     path: '*.deb'
