# Publish .deb packages to the Prebuilt-MPR.
name: Publish Package
on:
  pull_request:
    types:
      - closed

jobs:
  publish-pkg:
    name: Publish to Prebuilt-MPR
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Install needed dependencies
        run: sudo apt-get install libapt-pkg-dev -y
      - name: Download Prebuilt-MPR helper binary
        run: gh release download -p pbmpr -R "${{ github.repository }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Make Prebuilt-MPR helper binary executable
        run: chmod +x ./pbmpr
      - name: Upload packages to Prebuilt-MPR
        run: ./pbmpr upload-debs "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PROGET_TOKEN: "${{ secrets.PROGET_TOKEN }}"
      - name: Report succeeded build status
        run: gh pr comment "${{ github.event.pull_request.number }}" --body 'Package publishing has succeeded! :tada:' -R "${{ github.repository }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Report failed build status
        if: failure()
        run: gh pr comment "${{ github.event.pull_request.number }}" --body '**Package publishing has failed @makedeb/prebuilt-mpr-developers!** Please look over the [Checks tab](/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/checks) to see what went wrong.' -R "${{ github.repository }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
